# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 16:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=b'')),
                ('url', models.URLField(blank=True)),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('species', models.CharField(max_length=100)),
                ('count', models.CharField(default='', max_length=20)),
                ('females', models.CharField(default='', max_length=20)),
                ('males', models.CharField(default='', max_length=20)),
                ('young', models.CharField(default='', max_length=20)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('camera_type', models.CharField(default='', max_length=100)),
                ('latitude', models.CharField(default='', max_length=25)),
                ('longitude', models.CharField(default='', max_length=25)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Sites',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.AddField(
            model_name='observation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify.Person'),
        ),
        migrations.AddField(
            model_name='image',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify.Site'),
        ),
    ]
