# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['date'], 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['created_on'], 'verbose_name_plural': 'Observations'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['user'], 'verbose_name_plural': 'Persons'},
        ),
        migrations.AddField(
            model_name='species',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='description_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='species',
            name='latin_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='observation',
            name='count',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='observation',
            name='females',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='observation',
            name='males',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='observation',
            name='young',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='camera_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='latitude',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='site',
            name='longitude',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
