# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 20:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0004_auto_20170412_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
