# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0005_auto_20170412_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='date_str',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
